# Auto-enable loadbalancer only if metallb is enabled
ingress_nginx_loadbalancer: "{{ metallb_enabled }}"
ingress_nginx_loadbalancer_type: metallb
ingress_nginx_loadbalancer_metallb_pool: "{{ 'ingress' if 'ingress' in (metallb_additional_address_pools.keys()|list) else 'loadbalanced' }}"
