- name: Build kubespray inventory
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    _infile: "{{infile|default('../cluster_inventory.yml')}}"
    _outfile: "{{outfile|default('../inventory.ini')}}"
    cluster_inventory: "{{ lookup('file', _infile) | from_yaml }}"
  tasks:
  - template:
      dest: "{{_outfile}}"
      src: ../templates/inventory.ini.j2
    vars:
      master_nodes: '{{cluster_inventory|selectattr("type", "equalto", "master")|list}}'
      worker_nodes: '{{cluster_inventory|selectattr("type", "equalto", "worker")|list}}'
